name: Build and Test

on:
  # 手动触发构建
  workflow_dispatch:
    inputs:
      branch:
        description: '要构建的分支'
        required: true
        default: 'develop'
        type: choice
        options:
        - 'develop'
        - 'main'
      run_tests:
        description: '是否运行完整测试'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'
  # 仅在PR到main分支时自动触发
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.head_ref || github.ref }}
      
    - name: 显示构建信息
      run: |
        echo "=== 构建信息 ==="
        echo "触发方式: ${{ github.event_name }}"
        echo "构建分支: ${{ github.event.inputs.branch || github.head_ref || github.ref }}"
        echo "运行测试: ${{ github.event.inputs.run_tests || 'true' }}"
        echo "提交SHA: ${{ github.sha }}"
        echo "==================="

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller>=5.0.0
        
    - name: 验证项目结构
      run: |
        echo "=== 项目结构检查 ==="
        Get-ChildItem -Force
        echo "=== src目录 ==="
        Get-ChildItem src/ -Force
        echo "=== assets目录 ==="
        if (Test-Path "src/assets") { Get-ChildItem src/assets/ -Force } else { echo "assets目录不存在" }

    - name: 运行代码质量检查
      run: |
        echo "=== 代码质量检查 ==="
        python scripts/dev_tools.py quality
        echo "质量检查完成"

    - name: 运行CI测试
      if: github.event.inputs.run_tests == 'true' || github.event_name == 'pull_request'
      run: |
        echo "=== 运行CI安全测试 ==="
        python scripts/ci_tests.py

    - name: 构建应用程序
      run: |
        echo "=== 构建应用程序 ==="
        python scripts/build.py
        
    - name: 验证构建结果
      run: |
        echo "=== 验证构建结果 ==="
        if (Test-Path "dist/BadgePatternTool.exe") {
          $size = (Get-Item "dist/BadgePatternTool.exe").Length / 1MB
          echo "✅ 构建成功，文件大小: $([math]::Round($size, 1)) MB"
        } else {
          echo "❌ 构建失败，未找到可执行文件"
          exit 1
        }
        
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ github.event_name == 'workflow_dispatch' && format('manual-build-{0}-{1}', github.event.inputs.branch, github.sha) || format('pr-build-{0}', github.sha) }}
        path: |
          dist/
        retention-days: 7
