name: Build and Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller>=5.0.0
        
    - name: Verify project structure
      run: |
        echo "=== Project Structure Check ==="
        Get-ChildItem -Force
        echo "=== src directory ==="
        Get-ChildItem src/ -Force
        echo "=== assets directory ==="
        if (Test-Path "src/assets") { Get-ChildItem src/assets/ -Force } else { echo "assets directory not found" }

    - name: Run code quality checks
      run: |
        echo "=== Code Quality Check ==="
        python scripts/dev_tools.py quality
        echo "Quality check completed"

    - name: Run CI tests
      run: |
        echo "=== Running CI Safety Tests ==="
        python scripts/ci_tests.py

    - name: Build application
      run: |
        echo "=== Building Application ==="
        python scripts/build.py
        
    - name: Verify build output
      run: |
        echo "=== Verify Build Results ==="
        if (Test-Path "dist/BadgePatternTool.exe") {
          $size = (Get-Item "dist/BadgePatternTool.exe").Length / 1MB
          echo "Build successful, file size: $([math]::Round($size, 1)) MB"
        } else {
          echo "Build failed, executable not found"
          exit 1
        }
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-${{ github.sha }}
        path: |
          dist/
        retention-days: 7
