name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.4.2)'
        required: true
        default: '1.4.2'
      create_release:
        description: '是否创建GitHub Release'
        required: true
        default: 'true'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  manual-release:
    runs-on: windows-latest

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller>=5.0.0
        
    - name: 更新版本号（如果需要）
      run: |
        $version = "${{ github.event.inputs.version }}"
        echo "=== 更新版本号到 $version ==="
        python scripts/version_manager.py $version --force

    - name: 构建可执行文件
      run: |
        echo "=== 构建可执行文件 ==="
        python scripts/build.py
        
    - name: Create release package
      run: |
        $version = "${{ github.event.inputs.version }}"
        $zipName = "BadgePatternTool-v$version-Windows-Manual.zip"
        
        mkdir manual-release
        Copy-Item "dist/BadgePatternTool.exe" "manual-release/"
        Copy-Item "dist/CHANGELOG.md" "manual-release/" -ErrorAction SilentlyContinue
        
        if (Test-Path "dist/docs") {
          Copy-Item "dist/docs" "manual-release/" -Recurse
        }
        
        Compress-Archive -Path "manual-release/*" -DestinationPath $zipName
        echo "ZIP_NAME=$zipName" >> $env:GITHUB_ENV

    - name: 创建简单发布说明
      if: github.event.inputs.create_release == 'true'
      run: |
        echo "=== 创建简单发布说明 ==="
        $version = "v${{ github.event.inputs.version }}"
        $buildTime = "${{ github.run_id }}"

        $releaseNotes = @"
        # BadgePatternTool $version (手动发布)

        这是一个手动触发的发布版本。

        ## 下载
        - 手动构建: ``BadgePatternTool-$version-Windows-Manual.zip``

        ## 安装说明
        1. 解压ZIP文件
        2. 运行 ``BadgePatternTool.exe``
        3. 查看 ``CHANGELOG.md`` 了解更新信息

        构建ID: $buildTime
        "@

        $releaseNotes | Out-File -FilePath "release_notes.md" -Encoding UTF8
        echo "简单发布说明已创建"

    - name: Create Release (if requested)
      if: github.event.inputs.create_release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: BadgePatternTool v${{ github.event.inputs.version }} (Manual Release)
        body_path: release_notes.md
        files: |
          ${{ env.ZIP_NAME }}
          dist/BadgePatternTool.exe
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Manual-Release-v${{ github.event.inputs.version }}
        path: |
          dist/
          manual-release/
          *.zip
        retention-days: 7
