name: Quality Check

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'img/**'
      - '.gitignore'

jobs:
  quality-check:
    runs-on: ubuntu-latest

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1
      QT_QPA_PLATFORM: offscreen
      DISPLAY: ":99"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies for PySide6
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libegl1-mesa-dev \
          libxrandr2 \
          libxss1 \
          libxcursor1 \
          libxcomposite1 \
          libasound2-dev \
          libxi6 \
          libxtst6 \
          xvfb \
          libxkbcommon-x11-0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-randr0 \
          libxcb-render-util0 \
          libxcb-xinerama0 \
          libfontconfig1 \
          libdbus-1-3

    - name: Setup virtual display
      run: |
        sudo Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 验证项目结构
      run: |
        echo "=== 项目结构检查 ==="
        python -c "
        import os
        from pathlib import Path

        # 检查关键目录
        dirs = ['src', 'src/common', 'src/core', 'src/ui', 'src/utils', 'scripts', 'tests']
        for d in dirs:
            if Path(d).exists():
                print(f'✅ {d}/ 目录存在')
            else:
                print(f'❌ {d}/ 目录缺失')

        # 检查关键文件
        files = ['src/main.py', 'src/common/constants.py', 'requirements.txt', 'BadgePatternTool.spec']
        for f in files:
            if Path(f).exists():
                print(f'✅ {f} 存在')
            else:
                print(f'❌ {f} 缺失')
        "

    - name: 运行代码质量检查
      run: |
        echo "=== 代码质量检查 ==="
        python scripts/dev_tools.py quality
        echo "质量检查完成"

    - name: 运行CI安全测试
      run: |
        echo "=== 运行CI安全测试 ==="
        python scripts/ci_tests.py
        echo "CI测试完成"
