name: Quality Check

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'img/**'
      - '.gitignore'

jobs:
  quality-check:
    runs-on: ubuntu-latest

    env:
      PYTHONIOENCODING: utf-8
      PYTHONUTF8: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 运行代码质量检查
      run: |
        echo "=== 代码质量检查 ==="
        python scripts/dev_tools.py quality
        echo "质量检查完成"

    - name: 运行轻量级测试
      run: |
        echo "=== 运行轻量级测试 ==="
        python scripts/ci_tests.py
        echo "轻量级测试完成"

    - name: 检查项目结构
      run: |
        echo "=== 项目结构检查 ==="
        ls -la
        echo "=== src目录 ==="
        ls -la src/
        echo "=== 检查关键文件 ==="
        test -f src/main.py && echo "✅ main.py 存在" || echo "❌ main.py 缺失"
        test -f src/common/constants.py && echo "✅ constants.py 存在" || echo "❌ constants.py 缺失"
        test -f requirements.txt && echo "✅ requirements.txt 存在" || echo "❌ requirements.txt 缺失"
